In [6]:
import numpy as np
import pandas as pd
n = 1000
usia = np.random.randint(20, 45, size=n)
gender = np.random.choice(['L', 'P'],size=n)
pendidikan = np.random.choice(['SMA','Diploma','Sarjana','Magister'], size=n)
pengalaman = np.random.poisson(3, size=n)
tes_tulis = np.random.normal(70, 10, size=n).clip(0, 100)
tes_wawancara = np.random.normal(75, 8, size=n).clip(0, 100)
keahlian = np.random.choice(['Dasar','Menengah','Lanjutan'], size=n)
kesesuaian = np.random.choice(['Rendah','Sedang','Tinggi'], size=n)
minat = np.random.choice(['Rendah','Sedang','Tinggi'], size=n)
diterima = np.random.choice(['Ya','Tidak','Mungkin'],size=n)

df = pd.DataFrame({
    'usia' : usia,
    'gender' : gender,
    'pendidikan': pendidikan,
    'pengalaman' : pengalaman,
    'tes_tulis' : tes_tulis,
    'tes_wawancara' : tes_wawancara,
    'keahlian' : keahlian,
    'kesesuaian' : kesesuaian,
    'minat' : minat,
    'diterima' : diterima
})

print(df)
print(df.info()) 
print(df.head())

df.to_csv("Data Tes Interview.csv")

     usia gender pendidikan  pengalaman  tes_tulis  tes_wawancara  keahlian  \
0      32      L   Magister           3  70.737501      75.221896  Lanjutan
1      31      P        SMA           4  76.324203      81.946117  Menengah
2      30      P        SMA           2  57.193484      69.662526     Dasar
3      23      P    Diploma           3  71.960684      82.375377  Lanjutan
4      29      P        SMA           1  57.205114      68.874532  Lanjutan
..    ...    ...        ...         ...        ...            ...       ...
995    34      L    Diploma           3  74.485285      65.534042  Lanjutan
996    37      P    Sarjana           4  76.945274      74.964829     Dasar
997    29      L   Magister           3  75.320388      59.265454  Lanjutan
998    37      L    Diploma           1  67.697632      68.859477     Dasar
999    21      P    Sarjana           3  77.610590      73.615495     Dasar

    kesesuaian   minat diterima
0       Rendah  Sedang    Tidak
1       Rendah  Rendah  Mungkin
2       Tinggi  Tinggi       Ya
3       Tinggi  Tinggi       Ya
4       Sedang  Sedang       Ya
..         ...     ...      ...
995     Sedang  Tinggi  Mungkin
996     Rendah  Sedang  Mungkin
997     Tinggi  Sedang       Ya
998     Rendah  Sedang       Ya
999     Sedang  Sedang    Tidak

[1000 rows x 10 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   usia           1000 non-null   int32
 1   gender         1000 non-null   object
 2   pendidikan     1000 non-null   object
 3   pengalaman     1000 non-null   int32
 4   tes_tulis      1000 non-null   float64
 5   tes_wawancara  1000 non-null   float64
 6   keahlian       1000 non-null   object
 7   kesesuaian     1000 non-null   object
 8   minat          1000 non-null   object
 9   diterima       1000 non-null   object
dtypes: float64(2), int32(2), object(6)
memory usage: 70.4+ KB
None
   usia gender pendidikan  pengalaman  tes_tulis  tes_wawancara  keahlian  \
0    32      L   Magister           3  70.737501      75.221896  Lanjutan
1    31      P        SMA           4  76.324203      81.946117  Menengah
2    30      P        SMA           2  57.193484      69.662526     Dasar
3    23      P    Diploma           3  71.960684      82.375377  Lanjutan
4    29      P        SMA           1  57.205114      68.874532  Lanjutan

  kesesuaian   minat diterima
0     Rendah  Sedang    Tidak
1     Rendah  Rendah  Mungkin
2     Tinggi  Tinggi       Ya
3     Tinggi  Tinggi       Ya
4     Sedang  Sedang       Ya